name: NPM Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  localStorage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm --prefix ./packages/localStorage install
      - run: npm --prefix ./packages/localStorage run test:ci
      - run: npm --prefix ./packages/localStorage run build
      - run: npm --prefix ./packages/localStorage publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  sessionStorage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm --prefix ./packages/sessionStorage install
      - run: npm --prefix ./packages/sessionStorage run test:ci
      - run: npm --prefix ./packages/sessionStorage run build
      - run: npm --prefix ./packages/sessionStorage publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
